mongodb :
  uri : mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
elasticSearch :
  workerNum : 5
  waitQueueTime : 10
jwt :
  jwtSecret : long-long
  jwtExpirationMs : 86400000